language: rust

env:
  CARGO_FEATURES: "--features nalgebra_affine,ndarray_volumes"

matrix:
  include:
    - rust: nightly
      os: linux
    - rust: stable
      os: windows
    - rust: stable
      os: osx
    - env:
        CROSS_TARGET: mips64-unknown-linux-gnuabi64
      rust: stable
      services: docker
      sudo: required
  allow_failures:
    - rust: nightly

before_script:
  - if [ ! -z "$CROSS_TARGET" ]; then
      rustup target add $CROSS_TARGET;
      cargo install cross --force;
      export CARGO_CMD="cross";
      export TARGET_PARAM="--target $CROSS_TARGET";
    else
      export CARGO_CMD=cargo;
      export TARGET_PARAM="";
    fi

script:
  - $CARGO_CMD test $TARGET_PARAM $CARGO_FEATURES
