[package]
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "Rust implementation of the NIfTI file format"
license = "MIT/Apache-2.0"
name = "nifti"
readme = "README.md"
version = "0.1.0"

[dependencies]
acc_reader = "*"
byteorder = "^1.0.0"
flate2 = "0.2.19"
ndarray = "^0.9.1"
quick-error = "1.2.0"
seek_bufread = "1.2.0"

[dev-dependencies]
pretty_assertions = "0.2.0"
