[package]
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
categories = ["parser-implementations"]
description = "Rust implementation of the NIfTI file format"
keywords = ["nifti", "neuroimaging", "standard", "parser"]
license = "MIT/Apache-2.0"
name = "nifti"
readme = "README.md"
documentation = "https://docs.rs/crate/nifti"
repository = "https://github.com/Enet4/nifti-rs"
version = "0.2.0"

[[example]]
name = "niftidump"
path = "examples/niftidump/main.rs"

[badges]

[badges.travis-ci]
branch = "master"
repository = "Enet4/nifti-rs"

[dependencies]
byteorder = "1.1.0"
flate2 = "0.2.19"
num = "0.1.40"
num-derive = "0.1.41"
num-traits = "0.1.40"
quick-error = "1.2.0"

[dependencies.derive_builder]
version = "0.5.0"

[dependencies.ndarray]
optional = true
version = "0.10.10"

[dev-dependencies]
pretty_assertions = "0.3.4"

[features]
ndarray_volumes = ["ndarray"]
