[package]
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
categories = ["parser-implementations"]
description = "Rust implementation of the NIfTI file format"
documentation = "https://docs.rs/crate/nifti"
keywords = ["nifti", "neuroimaging", "standard", "parser"]
license = "MIT/Apache-2.0"
name = "nifti"
readme = "README.md"
repository = "https://github.com/Enet4/nifti-rs"
version = "0.3.1"

[badges]

[badges.travis-ci]
branch = "master"
repository = "Enet4/nifti-rs"

[dependencies]
asprim = "0.1.1"
byteorder = "1.2.1"
flate2 = "1.0.1"
num = "0.1.40"
num-derive = "0.1.41"
num-traits = "0.1.40"
quick-error = "1.2.0"
safe-transmute = "0.6.0"
derive_builder = "0.5.0"

[dependencies.ndarray]
optional = true
version = "0.10.12"

[dev-dependencies]
approx = "0.1.1"
pretty_assertions = "0.4.0"

[[example]]
name = "niftidump"
path = "examples/niftidump/main.rs"

[features]
ndarray_volumes = ["ndarray"]
