[package]
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "Rust implementation of the NIfTI file format"
license = "MIT/Apache-2.0"
name = "nifti"
readme = "README.md"
version = "0.1.0"

[badges]

[badges.travis-ci]
branch = "master"
repository = "Enet4/nifti-rs"

[dependencies]
byteorder = "1.0.0"
flate2 = "0.2.19"
num = "0.1.37"
num-derive = "0.1.40"
num-traits = "0.1.37"
quick-error = "1.2.0"

[dependencies.derive_builder]
version = "0.4.7"
features = ["struct_default"]

[dependencies.ndarray]
optional = true
version = "0.9.1"

[dev-dependencies]
pretty_assertions = "0.2.0"

[features]
ndarray_volumes = ["ndarray"]
